# For each Resource, which items should be considered components?
# required: the system should count as a very poor if this doesn't exist.
--- 
article: 
  optional: 
    - activity
  required: 
    - journal
book: 
  optional: 
    - activity
chapter: 
  optional: 
    - figure
    - finding
    - table
    - activity
contributor: 
  optional: 
    - person
    - organization
  required: []
dataset: 
  optional: 
    - activity
figure: 
  optional: 
    - activity
  required: 
    - image
finding: 
  optional: 
    - activity
generic: 
  optional: 
    - activity
image: 
  optional: 
    - activity
instrument: 
  optional: 
    - activity
journal: 
  optional: 
    - activity
model: 
  optional: 
    - activity
platform: 
  optional: 
    - activity
reference: 
  required: 
    - publication
report: 
  optional: 
    - figure
    - table
    - finding
    - chapter
    - activity
scenario: 
  optional: 
    - activity
table: 
  optional: 
    - activity
  required: 
    - array
webpage: 
  optional: 
    - activity
