# For each Resource, which items should be considered components?
# required: the scoring script should count as a very poor if this doesn't exist.
--- 
article: 
  optional: 
    - activity
  required: 
    - journal
activity:
  required: []
  optional: []
array:
  required: []
  optional: []
book: 
  optional: 
    - activity
  required: []
chapter: 
  optional: 
    - figure
    - finding
    - table
    - activity
  required: []
contributor: 
  optional: 
    - person
    - organization
  required: []
dataset: 
  optional: 
    - activity
  required: []
figure: 
  optional: 
    - activity
  required: 
    - image
finding: 
  optional: 
    - activity
  required: []
generic: 
  optional: 
    - activity
  required: []
image: 
  optional: 
    - activity
  required: []
instrument: 
  optional: 
    - activity
  required: []
journal: 
  optional: 
    - activity
  required: []
model: 
  optional: 
    - activity
  required: []
platform: 
  optional: 
    - activity
  required: []
reference: 
  required: 
    - publication
  optional: []
report: 
  optional: 
    - figure
    - table
    - finding
    - chapter
    - activity
  required: []
scenario: 
  optional: 
    - activity
  required: []
table: 
  optional: 
    - activity
  required: 
    - array
webpage: 
  optional: 
    - activity
  required: []
